#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt', git: 'https://github.com/opscode-cookbooks/apt.git'
cookbook 'build-essential'
cookbook 'rvm', git: 'https://github.com/fnichol/chef-rvm.git'
cookbook 'imagemagick', git: 'https://github.com/opscode-cookbooks/imagemagick.git'
cookbook 'pygments', git: 'https://github.com/phlipper/chef-pygments.git'
